<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sql</string>
		<string>ddl</string>
		<string>dml</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(^.*\([^\)]*$|^\s*(?i:select|insert|drop|if|else|create|alter|update))</string>
	<key>foldingStopMarker</key>
	<string>(^\s*\)|^\s*$|;$)</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>SQL Custom</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\n</string>
			<key>name</key>
			<string>meta.ending-space</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#round-brackets</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?=\t)</string>
			<key>end</key>
			<string>(?=[^\t])</string>
			<key>name</key>
			<string>meta.leading-space</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.odd-tab.tabs</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.even-tab.tabs</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\t)(\t)?</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?= )</string>
			<key>end</key>
			<string>(?=[^ ])</string>
			<key>name</key>
			<string>meta.leading-space</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.odd-tab.spaces</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.even-tab.spaces</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(  )(  )?</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(select|from|where|top|distinct|join|inner join|insert|into|order by|ASC|DESC|declare)\b)</string>
			<key>name</key>
			<string>keyword.other.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(go\s*\n))</string>
			<key>name</key>
			<string>keyword.other.go.sql</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.create.sql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.sql</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.sql</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:^\s*(create)\s+(aggregate|conversion|database|domain|function|group|(unique\s+)?index|language|operator class|operator|rule|schema|sequence|table|tablespace|trigger|type|user|view)\s+)(['"`])?(\w+)\4</string>
			<key>name</key>
			<string>declaration.create.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+(?:\.\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\s+(on\s+|(not\s+)?null)\b)</string>
			<key>name</key>
			<string>keyword.other.DDL.create.II.sql</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.create.sql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.sql</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:(drop)\s+(aggregate|conversion|database|domain|function|group|index|language|operator class|operator|rule|schema|sequence|table|tablespace|trigger|type|user|view))</string>
			<key>name</key>
			<string>declaration.drop.sql</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.create.sql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.table.sql</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.sql</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.other.cascade.sql</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:\s*(drop)\s+(table)\s+(\w+)(\s+cascade)?\b)</string>
			<key>name</key>
			<string>declaration.drop.sql</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.create.sql</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.table.sql</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:^\s*(alter)\s+(aggregate|conversion|database|domain|function|group|index|language|operator class|operator|rule|schema|sequence|table|tablespace|trigger|type|user|view)\s+)</string>
			<key>name</key>
			<string>declaration.alter.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@[a-zA-Z]\w+\b</string>
			<key>name</key>
			<string>variable.other.ampersand.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:^\s*([\(]{0,}select(\s+distinct)?|insert\s+into|update|delete|from|where|group\sby|and|union(\s+all)?|having|order\sby)\b)</string>
			<key>name</key>
			<string>keyword.other.DML.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\s+values\s+)</string>
			<key>name</key>
			<string>keyword.other.DML.II.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:(begin(\s+work)?|commit(\s+work)?|rollback(\s+work)?))</string>
			<key>name</key>
			<string>keyword.other.sql.LUW.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:(grant(\swith\sgrant\soption)?|revoke))</string>
			<key>name</key>
			<string>keyword.other.authorization.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(bigint|bigserial|bit|bit\svarying\(\d+\)|boolean|box|bytea|character\s(varying)?\(\d+\)|char\(\d+\)|var\schar\(\d+\)|cidr|circle|datetime|date|double\sprecision|inet|int|integer|interval\(\d+\)|line|lseg|macaddr|money|table|numeric(\(\d+,\d+\))?|oid|path|point|polygon|real|smallint|serial|text|times(\(\d+\))(\swithoutstimeszone)?|timestamp(s(\(\d+\))(\swithoutstimeszone)?)?|varchar(\(\d+\))?)\b)</string>
			<key>name</key>
			<string>storage.type.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(primary\s+key|references|on\sdelete(\s+cascade)?|check)\b)</string>
			<key>name</key>
			<string>storage.modifier.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\bin\b)</string>
			<key>name</key>
			<string>keyword.other.data-integrity.sql</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.sql</string>
			<key>swallow</key>
			<string>\\.</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
			<key>name</key>
			<string>string.quoted.other.backtick.sql</string>
			<key>swallow</key>
			<string>\\.</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:^\s*(comment\s+on\s+(table|column|aggregate|constraint|database|domain|function|index|operator|rule|schema|sequence|trigger|type|view))\s+.*?\s+(is)\s+)</string>
			<key>name</key>
			<string>keyword.other.object-comments.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>--.*$</string>
			<key>name</key>
			<string>comment.line.double-dash.sql</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.sql</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line.double-slash.sql</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>string.quoted.square-brackets.sql</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.sql</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#\{([^\}]*)\}</string>
					<key>name</key>
					<string>string.interpolation.sql</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>%\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>string.quoted.double.sql</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#\{([^\}]*)\}</string>
					<key>name</key>
					<string>string.interpolation.sql</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>/(?=\S.*/)</string>
			<key>end</key>
			<string>/</string>
			<key>name</key>
			<string>string.regexp.sql</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#\{([^\}]*)\}</string>
					<key>name</key>
					<string>string.interpolation.sql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\/</string>
					<key>name</key>
					<string>string.escaped-slash.sql</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>%r\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>string.regexp.modr.sql</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#\{([^\}]*)\}</string>
					<key>name</key>
					<string>string.interpolation.sql</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\/</string>
					<key>name</key>
					<string>constant.character.escaped.slash.sql</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:(=|\+|-|&lt;|&gt;|/|\*)|\b(like|is not null|is null|and|or|as)\b)</string>
			<key>name</key>
			<string>keyword.operator.sql</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>round-brackets</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.group.braces</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$base</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.sql</string>
	<key>uuid</key>
	<string>CAACC16D-4338-4993-BAD6-0E904BC8655C</string>
</dict>
</plist>
